YouTube "/c/" Type URL Conversion Error
Fixed bug in "youtube_channel_id.py" - "custom_url_to_channel_id"
Error: "TypeError: the JSON object must be str, not 'bytes'"
Experienced when attempting to convert "/c/" type urls.

Tested a version of keshbotics3 from Decemeber 2020, and recieved the same error, however, I recall it working around that time period. GIT logs don't show anything meaningful changed in this function. Difficult to pinpoint what caused this error to spring up.